version: "3.3"

services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./config/db.env
  backend:
    depends_on:
      - postgres_db
    build: ./plataforma_ead_backend/
    ports: [ "3000:3000" ]
    restart: "always"
    networks:
      - backend
    volumes:
      - ".:/home/node/app"
networks:
  backend:
    driver: bridge
volumes:
  postgres_db:
    driver: local
  backend:
    driver: local
